### PR TITLE
Add badges

### PR DESCRIPTION
**Pull request by nomego**
Add some badges (primarily to test CC branch change)

### CODE REVIEW

**Comment by cristinecula** [comment]
depfu badge! https://depfu.com/projects/9625/badges

**Comment by nomego** [comment]
For the PR, `github.ref` seems to resolve to `refs/pull/10/merge` but CC expects a branch name.. hasn't this been working..? I think some service has changed.
Anyway other PRs from Travis would just have been `README-badges` in this case

**Comment by cristinecula** [comment]
@nomego there is also an error reported:
https://github.com/Neovici/computing-lit-element/pull/10/checks?check_run_id=250663848#step:7:23

`/home/runner/work/_temp/ecbf0f71-1f79-4b00-8ed0-02b78ce154d1.sh: line 3: [: missing ']'`

**Review by dotpointer — APPROVED** [review]
Not sure how to test this, but it looks good.

**Pull request merged**
